name: autobet-build

on:
  push:
    paths-ignore: 
      - "LICENSE"
      - ".gitignore"
      - "docs/**"
      - "*.md"
      - "unused/**"
      - ".github/workflows/codeql-analysis.yml"
  pull_request:
    paths-ignore: 
      - "LICENSE"
      - ".gitignore"
      - "docs/**"
      - "*.md"
      - "unused/**"
      - ".github/workflows/codeql-analysis.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    # Steps for getting the name for this artifact
    # The artifact name has the followig format:
    # autobet-${LATEST_RELEASE_TAG}-YYYYmmdd-HHMMSS
    - name: Get latest release tag
      id: latest_release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: MarkusJx
        repo: autobet
        excludes: prerelease, draft
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d.%H%M%S')"
      shell: bash
    - name: Set version name
      id: version_name
      run: echo "::set-output name=version::autobet-${{ steps.latest_release.outputs.release }}-${{ steps.date.outputs.date }}"
      shell: bash
    - name: Print version name
      run: echo ${{ steps.version_name.outputs.version }}
      shell: bash
    
    # Retrieve caches
    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: |
          ~\AppData\Roaming\npm-cache
          **\node_modules
          autobetLib\node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**\package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    # Set the boost_root variable
    - name: Set boost root
      id: boost_root
      run: echo "::set-output name=boost_root::$BOOST_ROOT_1_69_0"
      shell: bash
    
    # Build steps
    # Downloads boost, runs 'npm install' and 'npm run-script pack'
    # To install all dependencies and package the application
    #- name: Install boost
    #  run: choco install -y boost-msvc-14.1
    - name: Run npm install
      run: npm install
    - name: Build
      run: npm run-script build
      env:
        BOOST_ROOT: ${{ steps.boost_root.outputs.boost_root }}
    - name: Package
      run: npm run-script pack
      env:
        BOOST_ROOT: ${{ steps.boost_root.outputs.boost_root }}
        GH_TOKEN: ${{ secrets.github_token }}
    
    # Upload the artifact
    - name: Upload unstable build
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.version_name.outputs.version }}
        path: dist/autobet.exe
